### ISSUE TITLE
EVAL: tuple in Function has no tuple_y

### ISSUE THREAD

**Issue by diemoell** [McJty/RFToolsControl#188] opened 2022-04-24 04:01 UTC
Issue description: EVAL: tuple in Function has no tuple_y
Steps to reproduce: 
I use the programmer to select EVEL:tuple there is no tuple_y in the function options

Versions:
* Minecraft: 1.16.5
* Forge: 36.2.20
* McJtyLib:1.16-5.1.6
* RFTools:1.16-2.1.3
* RFTools Control:1.16-4.0.16

**Comment by McJty** [comment] 2022-04-24 04:12
What do you mean exactly? You can use the tuple_y function to get the Y value out of a tuple

**Comment by diemoell** [comment] 2022-04-24 04:27
![javaw_HJF3vLRvRL](https://user-images.githubusercontent.com/68217554/164956623-9bdc2074-f00c-4342-a6be-8950f6cf1ee0.gif)
My problem is that tuple_y he doesn't have at all

**Comment by McJty** [comment] 2022-04-24 04:29
hmm that's strange. I'll check it out

**Comment by McJty** [comment] 2022-04-28 03:29
I can reproduce this but I don't know the reason yet

**Comment by diemoell** [comment] 2022-04-28 03:58
I found that this problem only occurs in RFToolsControl -1.16-4.0.12 and later versions

**Comment by McJty** [comment] 2022-04-30 03:47
Fixed in the latest version

**Closed as completed by McJty** 2022-04-30 03:47 UTC
