### ISSUE TITLE
Auto crafting waiting to the result even if the slot given to is null.

### ISSUE THREAD

**Issue by sp-guip** [McJty/RFToolsControl#10] opened 2016-10-01 16:06 UTC
When on a Program for auto crafting you mark the crafting Ok and don't specify a slot the program doesn't get terminated and as a result you can't request multiple operations in that case.
it would stop after one

**Comment by McJty** [comment] 2016-10-01 16:55
Can you show me a screenshot of the program? Because termination of the program is unrelated to crafting and I think you may have a green arrow pointing the wrong way

**Comment by sp-guip** [comment] 2016-10-01 17:18
In a minute by the way I double checked it and the green arrow was not pointing anywhere.

**Comment by sp-guip** [comment] 2016-10-01 17:33
http://imgur.com/a/tUXd4

**Comment by McJty** [comment] 2016-10-01 17:35
How much is the delay set at?

**Comment by sp-guip** [comment] 2016-10-01 17:36
1 second

**Comment by McJty** [comment] 2016-10-01 17:36
I cannot reproduce this... Weird

**Comment by McJty** [comment] 2016-10-01 17:37
Can you do ctrl-a and then ctrl-c in the programmer and paste the resulting program on bpaste.net and how that to me?

**Comment by sp-guip** [comment] 2016-10-01 17:38
sure
https://bpaste.net/show/81c3266df281

**Comment by McJty** [comment] 2016-10-01 17:38
What version of RFTools Control?

**Comment by sp-guip** [comment] 2016-10-01 17:39
latest-1.30

**Comment by sp-guip** [comment] 2016-10-01 17:41
by the way is it intended to be able to request crafting only while in gui?

**Comment by McJty** [comment] 2016-10-01 17:43
I imported your program and requested an item. The program marks the craft result as ok and ends. So I really don't understand the problem on your side.

And to answer your other question no. You can act on other types of events as well and initiate auto-crafting that way as well. As long as you have a way to identify what you want to craft you should be fine. And there are ways to do that (like for example with token items or so)

**Comment by McJty** [comment] 2016-10-01 17:44
Ah btw
Type 'reset' in the processor and try your program again to make sure

**Comment by sp-guip** [comment] 2016-10-01 17:45
did it and it didn't help and i meant requesting multiple

**Comment by McJty** [comment] 2016-10-01 17:46
Oh wait, *what* exactly are you doing? Describe the exact steps?

**Comment by sp-guip** [comment] 2016-10-01 17:47
going to the station. clicking shift+LCB and type 2,3,co'

**Comment by sp-guip** [comment] 2016-10-01 17:49
it only worked once I gave it a result...

**Comment by McJty** [comment] 2016-10-01 17:51
You type exactly 2,3,co??? What's that supposed to mean? Sorry. But I'm a bit confused and I have no clue what exactly you're doing

**Comment by sp-guip** [comment] 2016-10-01 17:52
sorry it means random nuber

**Comment by McJty** [comment] 2016-10-01 17:54
Ah now I got it. I can reproduce it. I'll see what I can do about it

**Comment by sp-guip** [comment] 2016-10-01 18:01
thanks
btw you can't  request a crafting whilst not in gui there is a Video that proves it do you want me to put a link here?

**Comment by McJty** [comment] 2016-10-01 18:04
I don't know what you mean by 'requesting a crafting' while not in the gui. The only way to craft requests is via the crafting station. So what do you mean by 'whilst not in gui'?

**Comment by McJty** [comment] 2016-10-01 18:08
That's not possible. The crafting is not done on that station. Crafting happens on the processor which doesn't even know that the gui is open

**Comment by sp-guip** [comment] 2016-10-01 18:08
https://www.youtube.com/watch?v=UOVsARQbXTQ 
8:57

**Comment by McJty** [comment] 2016-10-01 18:09
What does that proof? The items would have crafted even if he closed the gui

**Comment by sp-guip** [comment] 2016-10-01 18:11
sorry wrong part

**Comment by sp-guip** [comment] 2016-10-01 18:21
https://www.youtube.com/watch?v=P52v-IBm_y8 8:33
sorry...

**Comment by McJty** [comment] 2016-10-01 18:26
I don't see a problem there. Having the gui open or not has no effect at all on what it is doing. That's pure client side and the operations are done server side

**Comment by sp-guip** [comment] 2016-10-01 18:30
I don't find the video but I can reproduce it.
Do you wan't me to put a screenshot here?

**Comment by sp-guip** [comment] 2016-10-01 18:34
I'll open a new Issue

**Comment by sp-guip** [comment] 2016-11-07 19:34
have you found the cause?

**Comment by McJty** [comment] 2016-11-07 19:52
The cause of what? I don't see any problem. Not sure what to do with this report really

**Comment by McJty** [comment] 2016-11-07 19:53
Oh this has been fixed a while ago. Forgot to close this

**Closed by McJty** 2016-11-07 19:53 UTC
